name: portal
description: Student Portal Mobile Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  provider: ^6.0.1
  iconsax: ^0.0.8
  rounded_loading_button: ^2.0.9
  flutter_carousel_slider: ^1.0.8
  websafe_svg: ^2.0.0
  flutter_advanced_drawer: ^1.2.4
  bouncing_widget: ^2.0.0
  intl: ^0.17.0
  flutter_paystack: ^1.0.5+1
  flutterwave: ^1.0.1
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.9
  http: ^0.13.4
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  cloud_firestore: ^3.1.4
  fluttertoast: ^8.0.8
  local_auth: ^1.1.9
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  google_maps_flutter: ^2.1.1
  lottie: ^1.2.1
  flutter_staggered_animations: ^1.0.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  image_path: "assets/png/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/png/splash.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/jpg/
    - assets/svg/
    - assets/png/
    - assets/map/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
